app:
    resource: "@AppBundle/Controller/"
    type:     annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

ora_recipe:
    type: rest
    prefix: /api
    resource: "@ActivityStreamBundle/Resources/config/routes.yml"

main:
    path:      /
    defaults:  { _controller: ActivityStreamBundle:Main:homepage }
